### ISSUE TITLE
Problem with http-get

### ISSUE THREAD

**Issue by xPapla** [vanhauser-thc/thc-hydra#100]
Hello,
I have a problem whenever I try to use http-get testing my current router.
I tried:

``` bash
hydra -l user -p user 192.168.55.1 -m "/" http-get -d > hydra_logs.txt 2>&1
```

 but it finished with 

> 1 of 1 target completed, 0 valid passwords found

To be sure that everything is okay with login and password I also tried:

``` bash
wget --user=user --password=user http://192.168.55.1/ -d -o wget_logs.txt
```

and it has succeeded.

Full logs:
- [wget_logs.txt](https://github.com/vanhauser-thc/thc-hydra/files/170459/wget_logs.txt)
- [hydra_logs.txt](https://github.com/vanhauser-thc/thc-hydra/files/170460/hydra_logs.txt)

also a result of successful wget:
- [index.html](https://github.com/vanhauser-thc/thc-hydra/files/170462/index.html.txt)

**Comment by vanhauser-thc** [comment]
can you please check out the current repository state and see if it works?

if it does not, it is because your router is behaving non-standard, it seems to require a cookie: present.

**Comment by jamieOH** [comment]
I am also having issues and think it may be due to a cookie - but I haven't found any solid information of the syntax of how to add a cookie. Can you maybe link me a resource or tell me the basics?

**Comment by CookieMichal** [comment]
So, I cloned eb3628d and tried again, but still hydra fails - [full logs](http://termbin.com/z1j8)

**Comment by vanhauser-thc** [comment]
hi guys,

sorry, http-get does not support cookies at the moments - simply because they are not necessary.
it is the router that is non-standard.
the cookie functionality is present in the http-form module, so I (or somebody else) might port it at some point to support also this non-standard behaviour.
I currently do not have the time for it, I will put it on the TODO list though.
If one of you guy has the time to do it, that would be great.
