### ISSUE TITLE
Release tag missing for 8.2

### ISSUE THREAD

**Issue by xambroz** [vanhauser-thc/thc-hydra#132]
Hello,
the release tag is missing on github for the 8.2 release.
Please would you be able to tag it? 
Thank you
Michal Ambroz

**Comment by vanhauser-thc** [comment]
good idea, never did that.
the tag/release will however never be 100% compared to the .tar.gz on the thc.org web site, simply because github checkouts will always have the VERSION-dev marking so I have an indicator what people were using when reporting bugs.
(this 8.2 tag includes a few non imporant fixes like FSF address update that are not in the real 8.2 release)

**Comment by xambroz** [comment]
Well ... may be you can at least think of that for the next release. 
Like changing 8.3-dev to 8.3, tagging 8.3, changing to 8.4-dev ... so you would have the clean release tar.gz in the github which you can match with other distribution channels as well.
