### ISSUE TITLE
Firefox is flagging hydra website and SSL certs cannot be verified by wget

### ISSUE THREAD

**Issue by ilovezfs** [vanhauser-thc/thc-hydra#134]
Any idea what's going on? Given the current situation, I'm not sure Homebrew can continue to distribute this software at least until we understand the circumstances.

Firefox is saying,

> This web page at www.thc.org has been reported to contain unwanted software and has been blocked based on your security preferences.
> 
> Unwanted software pages try to install software that can be deceptive and affect your system in unexpected ways.

And wget is saying

> ERROR: cannot verify www.thc.org's certificate, issued by ‘CN=RapidSSL SHA256 CA - G3,O=GeoTrust Inc.,C=US’:
>   Unable to locally verify the issuer's authority.
> To connect to www.thc.org insecurely, use `--no-check-certificate'.

**Comment by vanhauser-thc** [comment]
Firefox/Chrome/Google: it is because dump Google people put the site on the "harmful" list. We never ever had any malicious content on our web site. It is just that they suck.

wget et al: an intermidiate CA key is not in the Linux default CA store, so wget is unable to verify the chain. Usually you would just add the cert to the local .pem file for Apache - however that is not my department on that server :)

**Comment by tdsmith** [comment]
Are you sure the server is sending the correct certificate chain? I think the intermediate certificate provided by the server might be incorrect. The server certificate is issued by `/C=US/O=GeoTrust Inc./CN=RapidSSL SHA256 CA - G3` and the provided intermediate certificate is `/C=US/O=GeoTrust, Inc./CN=RapidSSL CA`; they should match. I think this works in browsers because [browsers can use certificate metadata in the server certificate](http://stackoverflow.com/a/7644229/892260) to find the correct intermediate certificate even though the server is providing the wrong one.

**Comment by tdsmith** [comment]
You can get a look at the chain the server is providing with `openssl s_client -connect www.thc.org:443 -servername www.thc.org -showcerts`; you'll see that browsers are ignoring the intermediate CA certificate provided by www.thc.org.
