### ISSUE TITLE
[ERROR]: used ssh and it says 'terminal database is inaccessible '

### ISSUE THREAD

**Issue by euphrat1ca** [vanhauser-thc/thc-hydra#195]
i used hydra to connect some ips' ssh, but it says  'terminal database is inaccessible '. could you tell me why it can be this error?  thanks

**Comment by vanhauser-thc** [comment]
please post full screen output. I have no clue what you mean.

**Comment by euphrat1ca** [comment]
![image](https://cloud.githubusercontent.com/assets/23180818/23388776/3773c226-fd9f-11e6-8e4a-d5c3a93bbb0f.png)

1. I used Cygwin to complete the hydra on hydra.  then, the hydra can run, but when i used it to connect ssh, and it says like that.
2. Could you give me some advice on how to complete the hydra on windows with Cygwin.  I was followed the step on internet, but always failed in the end
![image](https://cloud.githubusercontent.com/assets/23180818/23388946/0097c256-fda0-11e6-9169-55b941c70a18.png)

**Comment by vanhauser-thc** [comment]
this is a problem with your system - not with hydra.

this might help: http://superuser.com/questions/319912/i-cant-clear-the-terminal-in-mac-os-x-lion-terminals-database-is-inaccessibl

also try to run hydra in a bash shell (click the cygwin terminal icon on your desktop and work from there)

**Comment by euphrat1ca** [comment]
thanks very much. 
but， could you give me some advice about how to translate the source code into windows with Cygwin?

**Comment by ataoyyt** [comment]
把/usr/include/term.h的文件名改掉，让configure找不到ncurses，然后重新configure/make就好了

**Comment by Xiangju** [comment]
In my case, the error was caused by using "conda create -c rdkit -n rdkit-env rdkit" (source link) to create a conda environment with the rdkit for Python3.7 on Mac. Otherwise, the clear command works fine for the other conda or virtual Python environments.

Adding the following line to ~/.bash_profile or ~/.bashrc solves the issue for me ([source link](https://github.com/conda/conda/issues/1368)):

export TERMINFO=/usr/share/terminfo

**Comment by Dawood340** [comment]
@Xiangju this doesn't work, however the echo $TERM give xterm-color256 back

**Comment by Dr-Hex** [comment]
This error caused by including **libncurses** support in build, where it cannot find required dependency files during the execution.
Solutions are the following:
* disable terminal colors support by removing libncurses from cygwin or by modifying **configure** script
* or include **usr/share/terminfo** folder in the location 1-level upper of your hydra's **cygwin1.dll**.
