### ISSUE TITLE
0 valid password found

### ISSUE THREAD

**Issue by Eyegabry99** [vanhauser-thc/thc-hydra#213]
Hi developer,
i have the error "1 of 1 target completed, 0 valid password found" 
but i know my pass and it is right. I tested it on port 25 and on port 80 but i had the same error. I also tried hydra -gtk but it doesn't work. 
i tried with "-P" command putting a file and with "-p" putting a string (my real password) and it doesn't work. I tried to test hydra on gmail service (smtp.google.com)

**Comment by tjgerot** [comment]
This is likely Google blocking your attempts. If you are convinced this is not the case, run the same command with verbose mode, `-V` (capital not lowercase), and include the necessary debugging information.

**Comment by KaliSentinelX** [comment]
@tjgerot  
Good day I'm having the same issue but not with Google. I have experienced this for multiple days and I have updated my system as well. 
Target droopy Vuln VM I have also tried this on my pen test lab on Asus router RT-AC3100 and against a few raspberry pi running raspian with the same results.
Linux host 4.9.0-kali4-amd64 #1 SMP Debian 4.9.25-1kali1 (2017-05-04) x86_64 GNU/Linux
Hydra v8.3 (c) 2016 by van Hauser/THC
Hydra (http://www.thc.org/thc-hydra) starting at 2017-05-21 16:56:32
[WARNING] You must supply the web page as an additional option or via -m, default path set to /
[DATA] max 16 tasks per 1 server, overall 64 tasks, 14344398 login tries (l:1/p:14344398), ~14008 tries per task
[DATA] attacking service http-get on port 80
[ATTEMPT] target 192.168.56.102 - login "admin" - pass "123456" - 1 of 14344398 [child 0] (0/0)
[ATTEMPT] target 192.168.56.102 - login "admin" - pass "12345" - 2 of 14344398 [child 1] (0/0)
[ATTEMPT] target 192.168.56.102 - login "admin" - pass "123456789" - 3 of 14344398 [child 2] (0/0)
[ATTEMPT] target 192.168.56.102 - login "admin" - pass "password" - 4 of 14344398 [child 3] (0/0)
[ATTEMPT] target 192.168.56.102 - login "admin" - pass "iloveyou" - 5 of 14344398 [child 4] (0/0)
[ATTEMPT] target 192.168.56.102 - login "admin" - pass "princess" - 6 of 14344398 [child 5] (0/0)
[ATTEMPT] target 192.168.56.102 - login "admin" - pass "1234567" - 7 of 14344398 [child 6] (0/0)
[ATTEMPT] target 192.168.56.102 - login "admin" - pass "rockyou" - 8 of 14344398 [child 7] (0/0)
[ATTEMPT] target 192.168.56.102 - login "admin" - pass "12345678" - 9 of 14344398 [child 8] (0/0)
[ATTEMPT] target 192.168.56.102 - login "admin" - pass "abc123" - 10 of 14344398 [child 9] (0/0)
[ATTEMPT] target 192.168.56.102 - login "admin" - pass "nicole" - 11 of 14344398 [child 10] (0/0)
[ATTEMPT] target 192.168.56.102 - login "admin" - pass "daniel" - 12 of 14344398 [child 11] (0/0)
[ATTEMPT] target 192.168.56.102 - login "admin" - pass "babygirl" - 13 of 14344398 [child 12] (0/0)
[ATTEMPT] target 192.168.56.102 - login "admin" - pass "monkey" - 14 of 14344398 [child 13] (0/0)
[ATTEMPT] target 192.168.56.102 - login "admin" - pass "lovely" - 15 of 14344398 [child 14] (0/0)
[ATTEMPT] target 192.168.56.102 - login "admin" - pass "jessica" - 16 of 14344398 [child 15] (0/0)
[80][http-get] host: 192.168.56.102   login: admin   password: princess
[80][http-get] host: 192.168.56.102   login: admin   password: 123456
[80][http-get] host: 192.168.56.102   login: admin   password: 12345
[80][http-get] host: 192.168.56.102   login: admin   password: 123456789
[80][http-get] host: 192.168.56.102   login: admin   password: password
[80][http-get] host: 192.168.56.102   login: admin   password: iloveyou
[80][http-get] host: 192.168.56.102   login: admin   password: 1234567
[80][http-get] host: 192.168.56.102   login: admin   password: rockyou
[80][http-get] host: 192.168.56.102   login: admin   password: 12345678
[80][http-get] host: 192.168.56.102   login: admin   password: abc123
[80][http-get] host: 192.168.56.102   login: admin   password: daniel
[80][http-get] host: 192.168.56.102   login: admin   password: lovely
[80][http-get] host: 192.168.56.102   login: admin   password: nicole
[80][http-get] host: 192.168.56.102   login: admin   password: babygirl
[80][http-get] host: 192.168.56.102   login: admin   password: monkey
[80][http-get] host: 192.168.56.102   login: admin   password: jessica
1 of 1 target successfully completed, 16 valid passwords found
Hydra (http://www.thc.org/thc-hydra) finished at 2017-05-21 16:56:35

If you need more information please let me know so that I may provide it for you. Thank you

**Comment by petrock6** [comment]
@KaliSentinelX 

Can you show us your command line parameters? Need to verify that you're actually using the parameters correctly. The OP was attacking SMTP, not http.

**Comment by vanhauser-thc** [comment]
@KaliSentinelX this is a completely different thing and you should not pollute an issue with something else.

your issue is most likely because your target is a web form, not basic auth, so the correct module would be http-form-post

**Comment by KaliSentinelX** [comment]
@vanhauser-thc not a problem thanks for the heads up. Great work by the way.

**Comment by gogo4141** [comment]
PROBLEM HELP PLEASE
Hydra v8.3 (c) 2016 by van Hauser/THC - Please do not use in military or secret service organizations, or for illegal purposes.

Hydra (http://www.thc.org/thc-hydra) starting at 2017-06-04 20:16:33
[DATA] max 15 tasks per 1 server, overall 64 tasks, 15 login tries (l:1/p:15), ~0 tries per task
[DATA] attacking service ftp on port 21
[STATUS] 28.00 tries/min, 28 tries in 00:01h, 1 to do in 00:01h, 15 active
[STATUS] 29.00 tries/min, 58 tries in 00:02h, 1 to do in 00:01h, 15 active
[STATUS] 29.33 tries/min, 88 tries in 00:03h, 1 to do in 00:01h, 15 active
[STATUS] 29.50 tries/min, 118 tries in 00:04h, 1 to do in 00:01h, 15 active
1 of 1 target completed, 0 valid passwords found
Hydra (http://www.thc.org/thc-hydra) finished at 2017-06-04 20:21:21

**Comment by vanhauser-thc** [comment]
@gogo4141 first update to newest version, then try again, then submit all output with -d option added.

**Comment by vanhauser-thc** [comment]
this issue can been polluted with too many bugs based on old version or user misuse.
I will therefore be closing this issue.

If you guys find an issue in this current github version (8.6-dev) that is not based on not being able to crack a password on gmail/hotmail or using http-get instead of http-form-get etc. please create a new issue.

**Comment by PythonKali** [comment]
I am getting the same error - 0 valid passwords found. I am trying hydra on my own account and the password I am using is my own password and it is valid. it is not gmail or any other email. I have tried both http and https but i keep getting same error , I have even tried -f and specified the port using -s option

the command i used was as below:

hydra -l <validusername> -p <validpassword> <validipaddress> -V http-form-post "/validurl.php:USER_NAME=^USER^&PSSWORD=^PASS^&Login=Login:F=Invalid"

I am entering my own username and password to see what hydra says and it says 0 valid password found. why is it doing that?

**Comment by 09himutyagi** [comment]
Hi 
i am using Hydra v9.3-dev version 
i am practicing on dvwa   . since 1 week i am continuously trying to brute force admin and pass field but i am getting error "1 of 1 target completed, 0 valid password found " i have a admin and password both in the list ..can anyone please help

COMMAND I AM USING :-
hydra -V  -t 1  -f  -l admin -P /home/tyagi/Desktop/golu.txt 192.168.1.45 http-form-get "/dvwa/vulnerabilities/brute/login.php:username=^USER^&password=^PASS^&Login=Login:username and/or password incorrect"

ERROR :-

[ATTEMPT] target 192.168.1.45 - login "admin" - pass "13345laptop" - 1 of 25 [child 0] (0/0)
[ATTEMPT] target 192.168.1.45 - login "admin" - pass "computer" - 2 of 25 [child 0] (0/0)
[ATTEMPT] target 192.168.1.45 - login "admin" - pass "screen" - 3 of 25 [child 0] (0/0)
[ATTEMPT] target 192.168.1.45 - login "admin" - pass "dvwa" - 4 of 25 [child 0] (0/0)
[ATTEMPT] target 192.168.1.45 - login "admin" - pass "bruteforce" - 5 of 25 [child 0] (0/0)
[ATTEMPT] target 192.168.1.45 - login "admin" - pass "sq" - 6 of 25 [child 0] (0/0)
[ATTEMPT] target 192.168.1.45 - login "admin" - pass "himu" - 7 of 25 [child 0] (0/0)
[ATTEMPT] target 192.168.1.45 - login "admin" - pass "tyagi" - 8 of 25 [child 0] (0/0)
[ATTEMPT] target 192.168.1.45 - login "admin" - pass "09" - 9 of 25 [child 0] (0/0)
[ATTEMPT] target 192.168.1.45 - login "admin" - pass "blackhat" - 10 of 25 [child 0] (0/0)
[ATTEMPT] target 192.168.1.45 - login "admin" - pass "facebook" - 11 of 25 [child 0] (0/0)
[ATTEMPT] target 192.168.1.45 - login "admin" - pass "xss" - 12 of 25 [child 0] (0/0)
[ATTEMPT] target 192.168.1.45 - login "admin" - pass "dom" - 13 of 25 [child 0] (0/0)
[ATTEMPT] target 192.168.1.45 - login "admin" - pass "cybersecurity" - 14 of 25 [child 0] (0/0)
[ATTEMPT] target 192.168.1.45 - login "admin" - pass "admin " - 15 of 25 [child 0] (0/0)
[ATTEMPT] target 192.168.1.45 - login "admin" - pass "password" - 16 of 25 [child 0] (0/0)
[ATTEMPT] target 192.168.1.45 - login "admin" - pass "09himut" - 17 of 25 [child 0] (0/0)
[ATTEMPT] target 192.168.1.45 - login "admin" - pass "admin" - 18 of 25 [child 0] (0/0)
[ATTEMPT] target 192.168.1.45 - login "admin" - pass "addpass" - 19 of 25 [child 0] (0/0)
[ATTEMPT] target 192.168.1.45 - login "admin" - pass "laptop" - 20 of 25 [child 0] (0/0)
[ATTEMPT] target 192.168.1.45 - login "admin" - pass "computer" - 21 of 25 [child 0] (0/0)
[ATTEMPT] target 192.168.1.45 - login "admin" - pass "screen" - 22 of 25 [child 0] (0/0)
[ATTEMPT] target 192.168.1.45 - login "admin" - pass "dvwa" - 23 of 25 [child 0] (0/0)
[ATTEMPT] target 192.168.1.45 - login "admin" - pass "bruteforce" - 24 of 25 [child 0] (0/0)
[ATTEMPT] target 192.168.1.45 - login "admin" - pass "sql" - 25 of 25 [child 0] (0/0)
1 of 1 target completed, 0 valid password found
Hydra (https://github.com/vanhauser-thc/thc-hydra) finished at 2021-06-09 04:25:18

PLEASE HELP

**Comment by nitinkumaralwariya** [comment]
1 of 1 target completed, 0 valid password found

**Comment by atanu2679** [comment]
hydra -S -l test123@gmail.com -P /root/Desktop/aa -e ns -V -s 465 smtp.gmail.com smtp

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2021-12-06 10:12:01
[INFO] several providers have implemented cracking protection, check with a small wordlist first - and stay legal!
[WARNING] Google Mail and others have bruteforce and hydra detection and send false positives. You are not doing anything illegal right?!
[WARNING] !read the above!
[DATA] max 14 tasks per 1 server, overall 14 tasks, 14 login tries (l:1/p:14), ~1 try per task
[DATA] attacking smtps://smtp.gmail.com:465/
[ATTEMPT] target smtp.gmail.com - login "test123@gmail.com" - pass "test123@gmail.com" - 1 of 14 [child 0] (0/0)
[ATTEMPT] target smtp.gmail.com - login "test123@gmail.com" - pass "" - 2 of 14 [child 1] (0/0)
[ATTEMPT] target smtp.gmail.com - login "test123@gmail.com" - pass "asfafafak" - 3 of 14 [child 2] (0/0)
[ATTEMPT] target smtp.gmail.com - login "test123@gmail.com" - pass "akdaldhad" - 4 of 14 [child 3] (0/0)
[ATTEMPT] target smtp.gmail.com - login "test123@gmail.com" - pass "ryiryif" - 5 of 14 [child 4] (0/0)
1 of 1 target completed, 0 valid password found
[WARNING] Writing restore file because 1 final worker threads did not complete until end.
[ERROR] 1 target did not resolve or could not be connected
[ERROR] 0 target did not complete
Hydra (https://github.com/vanhauser-thc/thc-hydra) finished at 2021-12-06 10:12:09

**Comment by Coke1x** [comment]
try downloading linux vm and then run the hydra command this way google won't block

**Comment by silentecho16** [comment]
1 of 1 target completed, 0 valid password found in hydra 9.5
