### ISSUE TITLE
segment fault in hydra 8.6

### ISSUE THREAD

**Issue by 1Tech-X** [vanhauser-thc/thc-hydra#247]
$hydra -l admin -P pass.txt 192.168.0.1 http-get
Hydra v8.6 (c) 2017 by van Hauser/THC - Please do not use in military or secret service organizations, or for illegal purposes.

Hydra (http://www.thc.org/thc-hydra) starting at 2017-08-14 17:11:36
[WARNING] You must supply the web page as an additional option or via -m, default path set to /
Segmentation fault

**Comment by vanhauser-thc** [comment]
does not happen for me.

did you compile it yourself?
what platform are you running on? (32/64, Linux distribution, VM type, etc)
and please attach a code (ulimit -c unlimited) and the hydra binary

**Comment by 1Tech-X** [comment]
i m running  in termux

**Comment by 1Tech-X** [comment]
$ hydra -l user -P passlist.txt ftp://192.168.0.1Hydra v8.6 (c) 2017 by van Hauser/THC - Please do not use in military or secret service organizations, or for illegal purposes.

Hydra (http://www.thc.org/thc-hydra) starting at 2017-08-18 20:45:47
Segmentation fault

**Comment by 1Tech-X** [comment]
always show segment fault 
what does it it's means 
PLEASE help

**Comment by vanhauser-thc** [comment]
please try:

git clone https://github.com/vanhauser-thc/thc-hydra
cd thc-hydra
./configure
-> edit Makefile and replace -O3 with -g (in the OPTS= line
make
make install
gdb hydra
(on gdb prompt):
  run -l user -P passlist.txt ftp://192.168.0.1
  (if hydra crashes):
     bt

and paste all output starting from the gdb output

**Comment by 1Tech-X** [comment]
[WARNING] You must supply the web page as an additional option or via -m, default path set to /

**Comment by 1Tech-X** [comment]
how to supply web page  as an additional option 
what is additional option 
before in hydra 8.5 and 8.1 i will never get this type of error or segment fault

**Comment by deargle** [comment]
@vanhauser-thc I'm also getting a segment fault for everything >v8.5. I followed your steps.

```
(gdb) run -l user -p passlist.txt ftp://192.168.0.1
Starting program: /root/thc-hydra/hydra -l user -p passlist.txt ftp://192.168.0.1
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".
Hydra v8.7-dev (c) 2017 by van Hauser/THC - Please do not use in military or secret service organizations, or for illegal purposes.

Hydra (http://www.thc.org/thc-hydra) starting at 2017-09-01 00:56:36

Program received signal SIGSEGV, Segmentation fault.
__strlen_ia32 () at ../sysdeps/i386/i686/multiarch/../../i586/strlen.S:51
51	../sysdeps/i386/i686/multiarch/../../i586/strlen.S: No such file or directory.
(gdb) bt
#0  __strlen_ia32 () at ../sysdeps/i386/i686/multiarch/../../i586/strlen.S:51
#1  0xb7a06190 in _IO_vfprintf_internal (s=<optimized out>, 
    format=<optimized out>, ap=0xbfff9ed4 "") at vfprintf.c:1637
#2  0xb7a06ab1 in buffered_vfprintf (s=s@entry=0xb7b75d60 <_IO_2_1_stdout_>, 
    format=format@entry=0x45d5e4 "[DATA] max %d task%s per %d server%s, overall %d task%s, %lu login tr%s (l:%lu/p:%lu), ~%lu tr%s per task\n", 
    args=args@entry=0xbfff9ea4 "\001") at vfprintf.c:2325
#3  0xb7a0444d in _IO_vfprintf_internal (s=0xb7b75d60 <_IO_2_1_stdout_>, 
    format=0x45d5e4 "[DATA] max %d task%s per %d server%s, overall %d task%s, %lu login tr%s (l:%lu/p:%lu), ~%lu tr%s per task\n", ap=0xbfff9ea4 "\001")
    at vfprintf.c:1293
#4  0xb7a0b966 in __printf (
    format=0x45d5e4 "[DATA] max %d task%s per %d server%s, overall %d task%s, %lu login tr%s (l:%lu/p:%lu), ~%lu tr%s per task\n") at printf.c:33
#5  0x004129e1 in ?? ()
#6  0xb79da286 in __libc_start_main (main=0x40b2e2, argc=6, argv=0xbffff3f4, 
    init=0x457f00, fini=0x457f60, rtld_fini=0xb7f11070 <_dl_fini>, 
    stack_end=0xbffff3ec) at ../csu/libc-start.c:291
#7  0x004035a1 in ?? ()
```

**Comment by vanhauser-thc** [comment]
I could reproduce this weird bug on my x64 VM.
So weird. The crash makes no sense at all.

this crashes:
printf("test %s test\n", a == 1 ? "foo" : "bar");

this does not:

printf("test ");
printf("%s", a == 1 ? "foo" : "bar");
printf(" test\n");

I did this as a work around. please update from the github repository and retest.

**Comment by deargle** [comment]
Confirmed working with that fix. Weird.

**Comment by vanhauser-thc** [comment]
thanks for verifying

**Comment by kubathorgal** [comment]
When I use command in gdb run -l user -P passlist.txt ftp://192.168.0.1 i get [ERROR] Unknown service: ftp://192.168.0.1

**Comment by vanhauser-thc** [comment]
I do not have that issue here. are you using a current version?
and why would you run it in gdb?

**Comment by kubathorgal** [comment]
I reinstalled the hydra yesterday and It didn't help but today everything works fine. So not an issue.

**Comment by vvv87** [comment]
Hi 👋, I’m completely new to this MARVELOUS WORLD and I’ll try to be clear as much as I possibly  can: I’ve recently installed(dual boot with vista) kali linux last version(32bit) onto an old machine(hp pavilion desktop pc with Intel Pentium 4 HT) and I’ve started to play around with some tools that kali offers; I’ve tested THC HYDRA(v8.6) on my own email with a pw list(12 pws only!!!) which includes the real pw too:   HYDRA runs(it initializes) but nothing happens, it just stops with no feedbacks whatsoever; ive checked and re-checked the syntax and settings and it seems all good; furthermore the only thing I’ve noticed is that as soon as I run HYDRA, 100% of the CPU is taken by this process(I’ve checked this by typing   ‘top’ on the console);  I URGENTLY NEED YOUR HELP and I’m deeply sorry I can’t post any scrn-shot cz im typing all this on my mobile and I’ll be back home in a couple of days, there’s no chance for me to post any pictures/else that could help explain my issue; 
However I’m trying to get ahead of it even if I’m away from my kali; before posting this I’ve checked in many forums about similar issues but the only thing I’ve found that could relate to my situation was right in here (https://github.com/vanhauser-thc/thc-hydra/issues/113) and the solution that has been suggested wasn’t very “appealing” to what I wanted(I don’t wanna downgrade to a previous HYDRA without even understanding where the issue is&without getting the related error outputs......(is that fair what I’m trying to say?😕).........anyway, please PLEASE PLEASE PLEASE, IM BEGGING YOU, any idea or suggestion or whatever it may be, would be IMMENSELY APPRECIATED and as soon as get to kali I’ll post all the related screenshots!

PS: please forgive me if in my first question I don’t even post a piece of evidence of what I’m trying to describe!

**Comment by deargle** [comment]
```
apt-get remove hydra
git clone https://github.com/vanhauser-thc/thc-hydra
cd thc-hydra
./configure
make
make install
```

Or something like that

**Comment by vvv87** [comment]
hi!!THANKS SO MUCH 4 the prompt replay!!.....I gave up my family weekend trip 2 get back 2 my Kali and try to sort it out and....here I am: so basically I've followed through your steps and I've ended up with Hydra v8.7( which is great !!)...the only thing is that i keep having the same issue: as soon as I initialize it, it just freezes(I mean the cursor on the console is blinking but no outputs at all)....no signs  whatsover.....and the same thing about the CPU usage, still @ 100%;
so this is the command I run:       

 hydra smtp.gmail.com smtp -l *********@gmail.com -P /root/Desktop/password/ -s 465 -S -v -V

and this is what I get:

root@vvv87:~# hydra smtp.gmail.com smtp -l ********@gmail.com -P /root/Desktop/password/ -s 465 -S -v -V
Hydra v8.7-dev (c) 2018 by van Hauser/THC - Please do not use in military or secret service organizations, or for illegal purposes.

[WARNING] hydra was compiled without SSL support. Install openssl and recompile! Option ignored...
Hydra (http://www.thc.org/thc-hydra) starting at 2018-01-05 17:29:18
[INFO] several providers have implemented cracking protection, check with a small wordlist first - and stay legal!
[WARNING] Google Mail has bruteforce detection and sends false positives. You are not doing anything illegal right?!


here is my scrnshot:

![4github](https://user-images.githubusercontent.com/35132421/34633070-2d7b30ca-f23f-11e7-9434-e2fbb659b292.jpeg)

PS:  I've just noticed the the [WARNING]  hydra was compiled without SSL support. Install openssl and recompile!.........this kind of warning was not present in the previous version(v8.6.1) i was running.....it was something else i don't really remember!......however I keep getting the same outcome and got stucked in here.
I have no idea where else I can put my hands on.

If there is anything I can provide you for further analysis on the matter  please let me know. I really appreciate your help

**Comment by vvv87** [comment]
I FORGOT THIS......
![forgotthis](https://user-images.githubusercontent.com/35132421/34633505-255245ca-f242-11e7-8b73-0f1fd09354fd.jpeg)

**Comment by kn81** [comment]
Above procedure worked for me
