### ISSUE TITLE
How do I connect to a ssh server with a user with empty password?

### ISSUE THREAD

**Issue by lundgrenolof** [vanhauser-thc/thc-hydra#266]
I have a server that Im trying to test. The default user is admin, with no password enabled. I didnt manage to find it using
`hydra -l admin -p "" myhost.com ssh`
the error message was 
```
user@kali:~$ hydra -l admin -p "" myhost.com ssh
Hydra v8.6 (c) 2017 by van Hauser/THC - Please do not use in military or secret service organizations, or for illegal purposes.

Hydra (http://www.thc.org/thc-hydra) starting at 2017-09-30 13:13:52
[WARNING] Many SSH configurations limit the number of parallel tasks, it is recommended to reduce the tasks: use -t 4
[DATA] max 1 task per 1 server, overall 1 task, 1 login try (l:1/p:1), ~1 try per task
[DATA] attacking ssh://myhost.com:22/
[ERROR] target ssh://myhost.com:22/ does not support password authentication.
```

if I set a password on admin user, I could successfully attack it with 
`hydra -l admin -p "pass" myhost.com ssh`

If I used regular SSH to connect to server, I came right in without entering password. 
```
user@kali:~$ ssh -V
OpenSSH_7.5p1 Debian-10, OpenSSL 1.0.2l  25 May 2017
```

**Comment by vanhauser-thc** [comment]
so "ssh admin@host" allows to log in without a password?
because sshd is usually configured to disallow empty passwords

**Comment by lundgrenolof** [comment]
Yes, more specifically a Mikrotik RouterOS device. Default user is admin with no password.

**Comment by vanhauser-thc** [comment]
can you please paste a session where you use ssh to login to the device without a password?
I want to be sure that the issue is in the libssh library - and not in your setup.

**Comment by vanhauser-thc** [comment]
let me clarify this because my comment can be misunderstood.

hydra is able to check for an empty password for ssh.

if it is not working for you there might be several issues e.g. different libssh version or unusual sshd implemention in your router - or passwordless login is not possible via ssh.

I made a small change in the code to see how the router replies.
clone and compile the github state, add the -d switch and paste all output

after you verified that passwordless ssh login is really possible

**Comment by vanhauser-thc** [comment]
any update here?
