### ISSUE TITLE
THC Hydra Not Working with RDP

### ISSUE THREAD

**Issue by JohnZombie** [vanhauser-thc/thc-hydra#352]
I am testing a bruteforce on a windows rdp server within a domain. It seems to not be working because nothing is locking out the account I am targeting. How do you specify a domain username? I tried username@domain.

`hydra -V -f -l username -P '/root/Desktop/linkedin_opt7ic.pot' rdp://targetip`

**Comment by JohnZombie** [comment]
I tested the account by manually handjamming the password several times and it locked. But when I use Hydra it does not lock the account.

**Comment by vanhauser-thc** [comment]
that is simply because the RDP module is currently not working against modern windows.

when you start hydra for rdp it also informs you about this:

```
[WARNING] the rdp module is currently reported to be unreliable, most likely against new Windows version. Please test, report - and if possible, fix.
```

the module would need to be rewritten and better use a library, e.g. libfreerdp. I sadly do not have the time for it, however me and the community would be happy to have a submission :)
