### ISSUE TITLE
THC Hydra Not Working with RDP

### ISSUE THREAD

**Issue by w0rhost** [vanhauser-thc/thc-hydra#362]
I am testing a bruteforce on a windows rdp server within a domain. It seems to not be working because nothing is locking out the account I am targeting. please help me!!!

hydra -l Administrator -p mypassword -t 4 rdp://targetip
Hydra v8.6 (c) 2017 by van Hauser/THC - Please do not use in military or secret service organizations, or for illegal purposes.

Hydra (http://www.thc.org/thc-hydra) starting at 2018-10-12 15:09:57
[WARNING] the rdp module is currently reported to be unreliable, most likely against new Windows version. Please test, report - and if possible, fix.
[DATA] max 1 task per 1 server, overall 1 task, 1 login try (l:1/p:1), ~1 try per task
[DATA] attacking rdp://targetip:3389/
[STATUS] 1.00 tries/min, 1 tries in 00:01h, 1 to do in 00:01h, 1 active
1 of 1 target completed, 0 valid passwords found
Hydra (http://www.thc.org/thc-hydra) finished at 2018-10-12 15:10:58

**Comment by baotang2118** [comment]
Me too. Hydra alway respone "1 of 1 target completed, 0 valid passwords found" although I give the correct user/password.

**Comment by vanhauser-thc** [comment]
duplicate #390

**Comment by baotang2118** [comment]
Ohm, I see

**Comment by baotang2118** [comment]
@w0rhost 
I found the answer for this topic even though it's not the official one. When Hydra hit the right user + password, it sit there for a while then quit program, it doesn't continue bruteforcing. This problem happens seem the server suddenly shutdown the connection and Hydra has to wait for connection time out. Although the output is:
[STATUS] 1.00 tries/min, 5 tries in 00:00h, 0 to do in 03:00h, 1 active
[STATUS] 0.83 tries/min, 5 tries in 00:00h, 0 to do in 03:00h, 1 active
[STATUS] 0.56 tries/min, 5 tries in 00:00h, 0 to do in 03:00h, 1 active
[STATUS] 0.36 tries/min, 5 tries in 00:00h, 0 to do in 03:00h, 1 active
[STATUS] 0.33 tries/min, 5 tries in 00:00h, 0 to do in 03:00h, 1 active
Press Ctrl+C. The last password that Hydra tried may be the correct password. I tried, it work for me. It only works for 1 username. I tried more than 1 username, then the progress stops because of so many attempt. Here is my script:
hydra -t 1 -V -f -l administrator -P wordlist.txt rdp://my_server_ip
Sometime you will see 1 of 1 target successfully completed, 0 valid password found

**Comment by ojohpeters** [comment]
> @w0rhost I found the answer for this topic even though it's not the official one. When Hydra hit the right user + password, it sit there for a while then quit program, it doesn't continue bruteforcing. This problem happens seem the server suddenly shutdown the connection and Hydra has to wait for connection time out. Although the output is:
> 
> ```
> [STATUS] 1.00 tries/min, 5 tries in 00:00h, 0 to do in 03:00h, 1 active
> [STATUS] 0.83 tries/min, 5 tries in 00:00h, 0 to do in 03:00h, 1 active
> [STATUS] 0.56 tries/min, 5 tries in 00:00h, 0 to do in 03:00h, 1 active
> [STATUS] 0.36 tries/min, 5 tries in 00:00h, 0 to do in 03:00h, 1 active
> [STATUS] 0.33 tries/min, 5 tries in 00:00h, 0 to do in 03:00h, 1 active
> ```
> 
> Press Ctrl+C. The last password that Hydra tried may be the correct password. I tried, it work for me. It only works for 1 username. I tried more than 1 username, then the progress stops because of so many attempt. Here is my script: `hydra -t 1 -V -f -l administrator -P wordlist.txt rdp://my_server_ip` Sometime you will see `1 of 1 target successfully completed, 0 valid password found`

thanks this worked for me
