### ISSUE TITLE
rdp module does not support the current protocol

### ISSUE THREAD

**Issue by sirty69** [vanhauser-thc/thc-hydra#390]
[ERROR] the rdp module does not support the current protocol, hence it is disabled. If you want to add it, please contact vh@thc.org

What's the problem ?

**Comment by vanhauser-thc** [comment]
that someone has to write the module to support the current protocol.
I dont have the time for that.

**Comment by baotang2118** [comment]
> [ERROR] the rdp module does not support the current protocol, hence it is disabled. If you want to add it, please contact [vh@thc.org](mailto:vh@thc.org)
> 
> What's the problem ?
@sirty69 @vanhauser-thc 
I found the answer for this topic even though it's not the official one. When Hydra hit the right user + password, it sit there for a while then quit program, it doesn't continue bruteforcing. This problem happens seem the server suddenly shutdown the connection and Hydra has to wait for connection time out. Although the output is:
`[STATUS] 1.00 tries/min, 5 tries in 00:00h, 0 to do in 03:00h, 1 active`
`[STATUS] 0.83 tries/min, 5 tries in 00:00h, 0 to do in 03:00h, 1 active`
`[STATUS] 0.56 tries/min, 5 tries in 00:00h, 0 to do in 03:00h, 1 active`
`[STATUS] 0.36 tries/min, 5 tries in 00:00h, 0 to do in 03:00h, 1 active`
`[STATUS] 0.33 tries/min, 5 tries in 00:00h, 0 to do in 03:00h, 1 active`
Press Ctrl+C. The last password that Hydra tried may be the correct password. I tried, it work for me. It only works for 1 username. I tried more than 1 username, then the progress stops because of so many attempt. Here is my script:
`hydra -t 1 -V -f -l administrator -P wordlist.txt rdp://my_server_ip`
Sometime you will see `1 of 1 target successfully completed, 0 valid password found`

**Comment by petercunha** [comment]
Bump. An RDP module would be very nice.

**Comment by petercunha** [comment]
thc is busy I suppose. I will do my best to code this and pull request.

God bless THC.

**Comment by vanhauser-thc** [comment]
I patch was submitted which uses libfreerdp.
Everyone please sync your github thc-hydra, configure, make, make install, test it and report!

**Comment by vanhauser-thc** [comment]
thanks a lot to @loianhtuan !

**Comment by zordis** [comment]
[ERROR] Compiled without FREERDP2 support, module not available!

How compiling with FREERDP2 support?

**Comment by loianhtuan** [comment]
> [ERROR] Compiled without FREERDP2 support, module not available!
> 
> How compiling with FREERDP2 support?

for ubuntu 18.04:
sudo apt install freerdp2-dev

**Comment by Crypto-Cat** [comment]
> 
> 
> > [ERROR] Compiled without FREERDP2 support, module not available!
> > How compiling with FREERDP2 support?
> 
> for ubuntu 18.04:
> sudo apt install freerdp2-dev

I still get the same error after installing freerdp2-dev. Tried reinstalling hydra but same problem.

**Comment by vanhauser-thc** [comment]
@Crypto-Cat  - reinstalling - you mean you synced the github repository, ./configure ; make ; make install?

or you reinstalled the version from your linux distro? that would not change anything, you need to compile from this repository.
if you compiled from here, are you sure that the hydra that is being executed is that one and not an old one? there could be another one in your path

**Comment by vanhauser-thc** [comment]
seems to work :)
