### ISSUE TITLE
Change user-agent for http-get

### ISSUE THREAD

**Issue by crewshon** [vanhauser-thc/thc-hydra#453]
How to change user agent that Hydra is sending? 
`Mozilla/4.0 (Hydra)`
It's blocking by default by WAF
Thanks!

**Comment by vanhauser-thc** [comment]
if what you do is legitimate then they should whitelist your IP for the WAF. otherwise the webapp pentest is pointless anyway. 
There are two ways to change it though, but if you cant find them ... well, maybe you should not ;)

**Comment by JsBergbau** [comment]
This page is one of the top results when searching for how to change the user agent. 
As far as I found out this is not possible. As far as I found out you have to recompile or use a proxy which overrides the user agent. I couldn't believe that this program has no ability to change User-Agent via command line or environment variables. Setting Headers via `:H=User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0` also didn't work.
This is very annoying since you now have to compile the program by yourself instead of using the provided package by your distribution and installing via packet-manager like apt. And additionally very annoying is that this program waves a flag "Hello I'm trying to do something you won't like" and nowhere is a warning about this. You have to check yourself by setting up a http server. Really really very annoying.

So to save people a lot of time here are the instructions of how to change user agent.
```
git clone https://github.com/vanhauser-thc/thc-hydra 
cd thc-hydra 
sed -r -i.bak 's#"User-Agent", "(.*)"#"User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0"#g' hydra-http-form.c
./configure
make
```
You can now run hydra via ./hydra in this folder or you can use make install. But why installing.

**Comment by JsBergbau** [comment]
This page is one of the top results when searching for how to change the user agent. Therefore it is extremely annonying not to write how to do this. 

And additionally very annoying that was this program literally does is waving a flat and screaming with a megaphone "YOU GOT ME, YOU GOT ME" and you don't get any warning about this. You have to check yourself by setting up a http server to see the default user agent `Mozilla/5.0 (Hydra)`. Extremely annoying.

You can change the User-Agent by adding `:H=User-Agent\: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv\:88.0) Gecko/20100101 Firefox/88.0`
Make sure to escape any occurence of `:` within the User-Agent String by `\`.

**Comment by jboomgaarden** [comment]
> This page is one of the top results when searching for how to change the user agent. Therefore it is extremely annonying not to write how to do this.
> 
> And additionally very annoying that was this program literally does is waving a flat and screaming with a megaphone "YOU GOT ME, YOU GOT ME" and you don't get any warning about this. You have to check yourself by setting up a http server to see the default user agent `Mozilla/5.0 (Hydra)`. Extremely annoying.
> 
> You can change the User-Agent by adding `:H=User-Agent\: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv\:88.0) Gecko/20100101 Firefox/88.0` Make sure to escape any occurence of `:` within the User-Agent String by `\`.

@JsBergbau how do you add that portion for the user-agent string? Can you give an example of a whole command line with hydra for doing this? When I attempted the following, I see two separate User Agent headers in the request...the default one for Hydra and the custom one I added.

**Comment by jboomgaarden** [comment]
@JsBergbau,

Seems to be an issue with 'http-get' vs 'http-get-form' or 'http-post-form'. Works as expected for the two form versions, but basic HTTP authentication attempts using just 'http-get' with a string like '/:H=User-Agent: Mozilla' and pcap is showing two separate User-Agent strings. Wondering if I'm doing something wrong or its an actual bug.

**Comment by JsBergbau** [comment]
For me this looks like a bug and you should open a new issue. There should never be 2 User-Agents and because hydra recognizes your user agent supplied by commandline it looks like a bug for me.

**Comment by jboomgaarden** [comment]
@JsBergbau agreed. Opened an issue: https://github.com/vanhauser-thc/thc-hydra/issues/763
