### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by mmf-Github** [vanhauser-thc/thc-hydra#476]
Hi there,

first of all - thanks for all the great work done here. I am trying to compile (either the latest version or 0.9) and I always hit some errors. With 0.9 I get "hydra-svn.c:110:102: error: 'svn_client_list_func2_t' undeclared" with the current version I hit "bfg.c:196:3: error: 'for' loop initial declarations are only allowed in C99 mode". When I switch on C99 mode in the makefile, I get a different error: hydra-time.c:7:18: error: storage size of 'ts' isn't known

I also fixed the error in bfg.c:196:3, but hit a different error.

Is there a trick to get this compiled at all? 

Thanks for any hint!

gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
CentOS Linux release 7.7.1908 (Core)

**Comment by vanhauser-thc** [comment]
why are you using an ancient compiler? if you move to gcc-5 or newer (and even 5 is ancient too) this program goes away. you should be able to install a newer gcc in your distro.

otherwise you will need to fix this. not by applying the c99 compile option, but fixing the source code: changing all

```
for (int i = 0; ...
```
to
```
int i;
for (i = 0; ...
```

there should be too many locations for this and this should be the only kind of compile problem.

make a pull request when done.

:)

**Comment by mmf-Github** [comment]
Yes, you're right - this gcc is ancient, but it's the one provided by the standard repos. I tried one of the more current ones still in the repos, but did not work out as well. I was looking for a version that is not so much hassle for Enterprise users (who cannot change the base system), but overlooked that Hydra is in the EPEL repo. All good from my end, thanks a lot!
