### ISSUE TITLE
0 valid password found

### ISSUE THREAD

**Issue by donowhattosay** [vanhauser-thc/thc-hydra#559]
i've been learning for hacking. i tried using hydra but when i tested it to my gmail account it said "0 valid password found" even thought i already put the right password to the dictionary. am i doing something wrong? is it the port?

command :

```hydra -l *******.*******@gmail.com -P D:\names.txt -e ns -V -S -s 465 smtp.gmail.com smtp```

![heheuh](https://user-images.githubusercontent.com/70560760/91796319-0db62f80-ec4a-11ea-9d67-2939c1b54ecf.JPG)

![failed](https://user-images.githubusercontent.com/70560760/91797955-0a24a780-ec4e-11ea-8aeb-d68a4389721e.JPG)
maybe someone can explain about the error? sorry im new

**Comment by vanhauser-thc** [comment]
1. only open one issue and comment in that, do not open multiple issue for the same problem
2. this is not a help forum, this is for reporting bugs in the software. if you want help there are many hacking/pentest forums where you can ask, sorry, my time is very, very limited.
3. your problem is that gmail and others have hacking protection, which hydra clearly states in the output if you would read it.
