### ISSUE TITLE
continue bruteforce after found password

### ISSUE THREAD

**Issue by synchronizy** [vanhauser-thc/thc-hydra#58]
how can I continue bruteforce after found password? or where I can find in the code string and modify this.
sorry for my bad english :)

**Comment by vanhauser-thc** [comment]
If a password is found for an account, no further cracking is performed for this account.
If this is not what you want, and look for more passwords that also report a success you have to restart hydra with a modified wordlist that has all entries removed up to the last found password.

**Comment by hefese** [comment]
I would like to get all found passwords instead of first one by using Brute force. But if I follow your suggestion that is related to restarting hydra again and again, I must use a dictionary instead of Brute Force. But if I use a dictionary, this file's size will be about 1TB and when I try to use 320-GB dictionary, hydra couldn't handle this. What do you suggestion?
