### ISSUE TITLE
How can i install hydra on termux

### ISSUE THREAD

**Issue by MohdAltaf01** [vanhauser-thc/thc-hydra#647]
1.What dependencies it takes.
2.Installation process same or not in Termux.
3.it can be work or not in Termux.
4.Why Hydra is not available in packages
![Screenshot_20210507-040420](https://user-images.githubusercontent.com/74550731/117373758-82ccb980-aee9-11eb-9b01-af51cb29ecf5.png)
![Screenshot_20210507-040457](https://user-images.githubusercontent.com/74550731/117373759-82ccb980-aee9-11eb-8713-347e46e73719.png)

**Comment by sanmacorz** [comment]
I'm also trying to install hydra on termux, and I tried compiling the source code from the latest stable release, but it has an error while compiling complaining about a not declared 'index', even though looking at the source code it is defined. Here is the error, maybe you can notice something wrong. Thanks!
![thc](https://user-images.githubusercontent.com/27830167/117556402-3d65d480-b02e-11eb-8568-1dabd33d0e1d.png)

**Comment by vanhauser-thc** [comment]
You can try to replace index() with strchr(). pleas report if it then compiles.

**Comment by vanhauser-thc** [comment]
I am on a vacation, so yes please do a pull request, thanks!

**Comment by Rajat01-beasty** [comment]
Sanmacorz i'm facing the same index problem can u guide me psl?

**Comment by Rajat01-beasty** [comment]
> > You can try to replace index() with strchr(). pleas report if it then compiles.
> 
> It worked! After changing that function in a couple files, it compiled properly and now can be opened with no problems. Should I try and make a pull request about this or has this already been discussed before?
> 
> ![hydra](https://user-images.githubusercontent.com/27830167/117898684-1fe17680-b28b-11eb-882c-a0e47f13b589.png)

How did you change the function

**Comment by sanmacorz** [comment]
> > > You can try to replace index() with strchr(). pleas report if it then compiles.
> > 
> > 
> > It worked! After changing that function in a couple files, it compiled properly and now can be opened with no problems. Should I try and make a pull request about this or has this already been discussed before?
> > ![hydra](https://user-images.githubusercontent.com/27830167/117898684-1fe17680-b28b-11eb-882c-a0e47f13b589.png)
> 
> How did you change the function

Well, you just have to replace all the "index(" for "strchr(" I did that on nano with ALT R and then just type what you want to do, you have to do that for all the references to the function so you can just do A for all, and I changed seven files: hydra-http-form.c, hydra-http-proxy-urlenum.c, hydra-http-proxy.c, hydra-http.c, hydra-mod.c, hydra-telnet.c, hydra.c. After changing all references to that function in these files, it worked for me. If while compiling it seems like it failed, try to run the program anyway, it's just a thing with Termux that fails everytime you try to compile something, even though it worked. Also I already did a pull request so if everything goes well, this should be fixed in a couple days.

**Comment by vanhauser-thc** [comment]
I accepted the PR, so if you freshly checkout or pull and try to recompile it should work for everyone.
thanks @sanmacorz

**Comment by sanmacorz** [comment]
Always happy to help 😄
