### ISSUE TITLE
Inconsistent behaviour with multiple tasks and -f or not -f

### ISSUE THREAD

**Issue by gblomqvist** [vanhauser-thc/thc-hydra#735]
**Describe the bug**
Suppose some login has several valid passwords (perhaps any password is accepted). If Hydra is used to brute-force the password of that login without the `-f` flag, then you will discover as many passwords as the number of Hydra tasks. However, if instead the `-f` flag is used, then exactly one login is found, regardless of the number of Hydra tasks.

**To Reproduce**

Running with 3 tasks without `-f` presents 3 passwords:
```console
$ hydra -l anonymous -P pw.txt -t3 -v ftp://127.0.0.1
...
[VERBOSE] Resolving addresses ... [VERBOSE] resolving done
[21][ftp] host: 127.0.0.1   login: anonymous   password: 123456
[STATUS] attack finished for 127.0.0.1 (waiting for children to complete tests)
[21][ftp] host: 127.0.0.1   login: anonymous   password: password
[21][ftp] host: 127.0.0.1   login: anonymous   password: 12345678
1 of 1 target successfully completed, 3 valid passwords found
...
```
Running with 3 tasks with `-f` presents 1 password:
```console
$ hydra -l anonymous -P pw.txt -t3 -v ftp://127.0.0.1 -f
...
[VERBOSE] Resolving addresses ... [VERBOSE] resolving done
[21][ftp] host: 127.0.0.1   login: anonymous   password: 123456
[STATUS] attack finished for 127.0.0.1 (valid pair found)
1 of 1 target successfully completed, 1 valid password found
...
```

**Expected behavior**
When a valid password is found, either all ongoing password attempts (in other tasks) should run to completion (like without `-f`), or the results of those other attempts should be ignored (like with `-f`).

**Desktop (please complete the following information):**
 - OS: Debian
 - hydra version: current github state

**Comment by vanhauser-thc** [comment]
Hi,
thanks for that great issue, rarely that someone provides all information.
I know about this. The reason that only one is reported with -f is that after the first is found everything else is canceled at once, so the other reports are not received and printed.
to have your wished behavior it would require that a list of which accounts per hosts have already been cracked and this is quite some overhead and extra work that I don't think is well spent - because if the other tasks also report different passwords working that is important information IMHO (you can see that either the test type is wrong (e.g. with http form setups), or that any password is ok).
So for me it works as expected and as it should be.
what do you think?

**Comment by gblomqvist** [comment]
I see. I agree that it can be valuable to know whether multiple passwords are deemed accepted. I'm not sure how exactly I would want it to work, and I understand that changing this behavior may require quite some changes. With that said, I'm closing this. Thanks for the clarification.
