### ISSUE TITLE
https-post-form with application/json gets stuck at "Use module https-get instead"

### ISSUE THREAD

**Issue by cseres3** [vanhauser-thc/thc-hydra#842]
**Describe the bug**
I was testing Hydra against Grafana login, the working curl prototype was
`curl --location --request POST 'https://example.com/login' -d '{"user":"someuser","password":"somepassword"}' -H "Content-Type: application/json"
`
and response either
`{"message":"Logged in"}`
or
`{"message":"Invalid username or password","traceID":"00000000000000000000000000000000"}`

However, Hydra got stuck into a forever loop when it was trying a wrong username/password:

`hydra -I -l wronguser -p wrongpass example.com https-post-form "/login:{\"user\"\:\"^USER^\",\"password\"\:\"^PASS^\"}:h=Content-Type\: application/json:Invalid"
Hydra v9.5-dev (c) 2023 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2023-05-03 17:36:51
[INFORMATION] escape sequence \: detected in module option, no parameter verification is performed.
[WARNING] Restorefile (ignored ...) from a previous session found, to prevent overwriting, ./hydra.restore
[DATA] max 1 task per 1 server, overall 1 task, 1 login try (l:1/p:1), ~1 try per task
[DATA] attacking http-post-forms://example.com:443/login:{"user"\:"^USER^","password"\:"^PASS^"}:h=Content-Type\: application/json:Invalid
[ERROR] the target is using HTTP auth, not a web form, received HTTP error code 401. Use module "https-get" instead.
[ERROR] the target is using HTTP auth, not a web form, received HTTP error code 401. Use module "https-get" instead.
[ERROR] the target is using HTTP auth, not a web form, received HTTP error code 401. Use module "https-get" instead.
[ERROR] the target is using HTTP auth, not a web form, received HTTP error code 401. Use module "https-get" instead.
[ERROR] the target is using HTTP auth, not a web form, received HTTP error code 401. Use module "https-get" instead.
^CThe session file ./hydra.restore was written. Type "hydra -R" to resume session.
`

(Error lines continued until Ctrl+c was pressed even though there was only one username/password to be checked)

**To Reproduce**
  * The bug was reproducable every time against Grafana login using the above mentioned command

**Expected behavior**
Hydra should have checked the user/password combination and continued to the next one, in this case just finished and reported about a wrong password

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.2 LTS
 - Hydra 9.5-dev

**Additional context**
I was able to solve the problem by modifying the source code in hydra-http-form.c so that Hydra continued to the next pair instead of printing out an error and getting stuck. A quick and dirty solution, but after that Hydra worked properly and was able to iterate through passwords.
[hydra-http-form.c-patch.txt](https://github.com/vanhauser-thc/thc-hydra/files/11383931/hydra-http-form.c-patch.txt)

**Comment by cseres3** [comment]
[hydra-command.txt](https://github.com/vanhauser-thc/thc-hydra/files/11384068/hydra-command.txt)
Sorry, the backslashes of the command dropped off while I was editing. I'll attach the command in a text file.

**Comment by vanhauser-thc** [comment]
add `-t 1 -d` to see a dump of the traffic. this will show you what is going wrong and likely you are not setting the parameters correctly.

**Comment by andraxin** [comment]
@vanhauser-thc
> add -t 1 -d to see a dump of the traffic. this will show you what is going wrong and likely you are not setting the parameters correctly.

This response isn't overly useful, considering that @cseres3 
had already described _exactly_ what is wrong *and* provided
a reasonable fix.

BTW, this is not the first time the issue was reported.
See, for example, https://github.com/vanhauser-thc/thc-hydra/issues/601, which you answered as
> that is an unusual setup. you can either patch that out of hydra and recompile - or if you think that is a useful feature make it a parameter in the miscptr, similar to H=, etc

https://github.com/vanhauser-thc/thc-hydra/issues/601#issuecomment-774029166

Personally, I don't think that's so unusual at all.  I experienced this 
exact same issue yesterday, and it's not all that uncommon that
_some_ web apps return `401` on failed authentication, rendering
the comment on line 974 potentially invalid.

https://github.com/vanhauser-thc/thc-hydra/blob/16b424af4db7f49d09b4a9157e805040ebff23ee/hydra-http-form.c#L974

I'm thinking that adding a parameter, say, `1=`  along the lines of `2=`
should help others in avoiding this pitfall (without having to recompile).
I'm hoping that makes @cseres3 's patch ready for general consumption.

https://github.com/vanhauser-thc/thc-hydra/pull/898
