### ISSUE TITLE
RDP brute force failed  with correct password

### ISSUE THREAD

**Issue by wgf4242** [vanhauser-thc/thc-hydra#921]
**Describe the bug**
Attempting an RDP brute force with correct user and password, but not found any valid password. 

**To Reproduce**
`hydra -vV -l test -p test -S rdp://192.168.127.130 -t 1`

**Desktop (please complete the following information):**
 - OS: kali 2023.3
 - hydra version 9.5

**Additional context**

```
$ hydra -vV -l test -p test -S rdp://192.168.127.130 -t 1
Hydra v9.5 (c) 2023 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2024-01-03 18:54:07
[WARNING] the rdp module is experimental. Please test, report - and if possible, fix.
[DATA] max 1 task per 1 server, overall 1 task, 1 login try (l:1/p:1), ~1 try per task
[DATA] attacking rdps://192.168.127.130:3389/
[VERBOSE] Resolving addresses ... [VERBOSE] resolving done
[ATTEMPT] target 192.168.127.130 - login "test" - pass "test" - 1 of 1 [child 0] (0/0)
[STATUS] attack finished for 192.168.127.130 (waiting for children to complete tests)
1 of 1 target completed, 0 valid password found
Hydra (https://github.com/vanhauser-thc/thc-hydra) finished at 2024-01-03 18:54:07
```

192.168.127.130 OS:
- Windows 7 x64 SP1

I can login with test/test using remote desktop.

**Comment by dmclazaro01** [comment]
I'm having the same problem with v9.6dev. RDP bruteforce matches passwords that are not valid. It's strange because I think that always find correctly the wordlist that has the password (I use a list of wordlists) but at the moment of choose the password always choose one that is wrong (and always before to try with the correct password).

The correct password is "root" and the tool thinks that is "letmein". I removed letmein from the wordlist  and tried again and choose another wrong password
![image](https://github.com/vanhauser-thc/thc-hydra/assets/93814183/212a4345-a768-4250-b854-5b7762621fb0)
![Captura de pantalla 2024-01-11 141817](https://github.com/vanhauser-thc/thc-hydra/assets/93814183/a1cc500d-dd1d-417f-98b7-cfbfc0fe1dac)

**Comment by vanhauser-thc** [comment]
follow up in #923

**Comment by vikramre1989** [comment]
FastRDP is a tool for brute force attacks on the Remote Desktop Protocol (RDP) on the Windows operating system, which allows users to remotely connect to computers and servers. This tool is written in C# programming language. Also, this tool has a Multi-threading feature that increases the efficiency and speed of testing simultaneous compounds.
I tested this tool, and it works great! I’ll put the link to this tool below.
[FastRDP](https://github.com/rensii-1996/RDP-Brute-Force)
